### ISSUE TITLE
Generate Code not in build or target Directory

### ISSUE THREAD

**Issue by amitjoy** [int128/gradle-swagger-generator-plugin#101]
Hi, I would like to generate the source codes in a separate directory rather than build or target directory. Is it possible in this plugin? So far, I was not able to generate it at all in a different directory other than the target.

**Comment by int128** [comment]
Yes. Try the `outputDir` option as like:

```
swaggerSources {
  petstore {
    inputFile = file('petstore.yaml')
    outputDir = file('your-custom-directory')
  }
}
```

**Comment by amitjoy** [comment]
Thanks @int128

**Comment by francispage** [comment]
Hi, actually, the correct syntax is inside code, not petstore. At least that's where it worked for me.

```
swaggerSources {
    petstore {
        petstore = file('swagger.yml')
        
        code {
            language = 'spring'
            configFile = file('config.json')
            components = ['models', 'apis']
            dependsOn validation
            outputDir = file('./mydir')
        }
    }
}
```

**Comment by int128** [comment]
@francispage Thanks! I just fixed my example.

**Comment by kigsmtua** [comment]
@francispage this will write a file to the specified directory rather create the directory can It be generated in a specific package without recreating the entire path
