### ISSUE TITLE
Cannot fully change outputDir

### ISSUE THREAD

**Issue by cleverbug** [int128/gradle-swagger-generator-plugin#106]
Im using the generateSwaggerCode command. Instead of generating the models in the build directory, I want them generated in `src/gen/java/com/cb/models`

So i have changed build.gradle:
 
`swaggerSources {
    petstore {
        inputFile = file('petstore.yaml')
        code {
            language = 'java'
            components = ['models']
            configFile = file('config.json')
            outputDir = file('src/gen/java/')
        }
    }
}`

And config.json is:

`{
  "dateLibrary": "java8",
  "hideGenerationTimestamp": true,
  "modelPackage": "com.cb.models"
}`

However, the models end up at `src/gen/java/src/main/java/com/cb/Pet.java`

I cannot figure out how to get rid of `src/main/java` in the path. Can this be done?

**Comment by int128** [comment]
You need to generate sources into a directory and move them to `src/gen/java`. This is due to limitation of swagger-codegen.
