### ISSUE TITLE
HTML Generation Documentation

### ISSUE THREAD

**Issue by bonehead06** [int128/gradle-swagger-generator-plugin#112]
I'm using version 2.11.0 and am trying to generate static HTML.  I see the documentation in your README for how to build the ReDoc or the Swagger UI, but there is nothing about static HTML.  I see in the main Swagger Codegen docs that it is possible by passing `-l html` as command line args, but I don't see a way to do it with this plugin.

**Comment by int128** [comment]
You can generate static HTML by code generation with `language = 'html'` or `language = 'html2'` option.
See the following examples in https://github.com/int128/gradle-swagger-generator-plugin/tree/master/acceptance-test.
> Working with Swagger Code Generator 2
> Basic example for HTML document generation
>
> Working with Swagger Code Generator 3
> Basic example for HTML document generation
