### ISSUE TITLE
Option to choose between V2 and V3

### ISSUE THREAD

**Issue by onkeljuergen** [int128/gradle-swagger-generator-plugin#114]
Hi,

it would be nice if one could have an option which code generator version to use.

E.g. if one has a very big project and multiple Yaml definitions it would be nice to define which code gen version to use for which yaml definition.

The main reason for this is that the OpenAPI specification breaks some specs of the old Swagger 2.0.
UUID is not supported anymore, as one example.

If I try to generate these old definitions with V3 then my old already deployed APIs will break.

Thanks in advance,
Jürgen

**Comment by int128** [comment]
Sounds good.
It may be possible to switch V2 and V3 by adding an option for setting dependency, as like:

```groovy
dependencies {
  swaggerCodegenV2 'io.swagger:swagger-codegen-cli:2.3.1'
  swaggerCodegenV3 'io.swagger.codegen.v3:swagger-codegen-cli:3.0.0'
}

swaggerSources {
  petstore {
    inputFile = file('petstore.yaml')
    code {
      language = 'spring'
      configFile = file('config.json')
      dependency = dependencies.swaggerCodegenV2 // default to dependencies.swaggerCodegen
    }
  }
}
```

I will add this feature in the future release.

**Comment by onkeljuergen** [comment]
Thanks for considering.

Looking forward to that release ;-)

**Comment by int128** [comment]
I just released the new version: https://github.com/int128/gradle-swagger-generator-plugin/releases/tag/2.15.0

**Comment by onkeljuergen** [comment]
Thanks a lot.
