### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by verglor** [int128/gradle-swagger-generator-plugin#120]
Is it possible to generate `swagger-spec.js` in UTF-8 encoding ? It seems to be encoded in CP1252. My source OpenAPI YAML is UTF-8 encoded and contains special unicode characters that are displayed incorrectly in Swagger UI.

**Comment by int128** [comment]
It depends on the system default charset for now.

It should be always UTF-8 and I will fix it later.
https://github.com/int128/gradle-swagger-generator-plugin/blob/master/src/main/groovy/org/hidetake/gradle/swagger/generator/GenerateSwaggerUI.groovy#L86

**Comment by int128** [comment]
Try the new version:
https://github.com/int128/gradle-swagger-generator-plugin/releases/tag/2.15.1
