### ISSUE TITLE
How to make ref files changes invalidate cache when running GenerateSwaggerCode?

### ISSUE THREAD

**Issue by gfjalar** [int128/gradle-swagger-generator-plugin#144]
## Question

I'm running `GenerateSwaggerCode` task on input `yaml` that contains multiple `$ref`s. With such a setup, gradle doesn't pick up referenced files as input files for the task. Hence, it caches the task output and doesn't rerun the task on content changes in any of the referenced files.

**What's the correct approach to both keep using gradle cache and rerun generation on ref changes?**

As a workaround, I've added the directory which contains the referenced files as `templateDir`. So now my codegen task definition looks like that:

```
devCodegen {
  inputFile = file("${projectDir}/src/main/swagger/schema/api.yml")
    code {
      language = "java"
      outputDir = file("${buildDir}/swagger/codegen/api")
      additionalProperties = [...]
      wipeOutputDir = false
      templateDir = file("${projectDir}/src/main/swagger/schema")
    }
  }
```

## Environment
Plugin version: `2.15.0`
Swagger Codegen version: `2.2.3`
Gradle version: `5.1.1`
Java version: `8`
OS: `OSX`

**Comment by gfjalar** [comment]
I think I got it. Specifying `code.input.files` seems to do the trick :)

```
devCodegen {
  inputFile = file("${projectDir}/src/main/swagger/schema/api.yml")
  code {
    input.files "${projectDir}/src/main/swagger/schema"
    language = "java"
    outputDir = file("${buildDir}/swagger/codegen/api")
    additionalProperties = [...]
    wipeOutputDir = false
  }
}
```

**Comment by anascotti** [comment]
`input.files` is not recognized by `GenerateSwaggerCode` task

```
> Could not get unknown property 'input' for task ':acquiring-core:generateSwaggerCode' of type org.hidetake.gradle.swagger.generator.GenerateSwaggerCode.
```

```
Plugin version: 2.18.2
Swagger Codegen version: 2.4.18
Gradle version: 6.8.3
```

**Comment by gfjalar** [comment]
> `input.files` is not recognized by `GenerateSwaggerCode` task
> 
> ```
> > Could not get unknown property 'input' for task ':acquiring-core:generateSwaggerCode' of type org.hidetake.gradle.swagger.generator.GenerateSwaggerCode.
> ```
> 
> ```
> Plugin version: 2.18.2
> Swagger Codegen version: 2.4.18
> Gradle version: 6.8.3
> ```

I probably missed trailing `s` in my workaround. You can try `inputs.file` instead. Because it's `getInputs` on `DefaultTask`, not `getInput` (https://docs.gradle.org/current/javadoc/org/gradle/api/Task.html#getInputs--).
