### ISSUE TITLE
unable to access swaggerUi documentation from the endpoint

### ISSUE THREAD

**Issue by oskarstucki** [int128/gradle-swagger-generator-plugin#176]
## Describe the bug

To Reproduce: I have the plugin setup like this

```
def swaggerSourceFile = "$projectDir/api/api.yaml"
def openAPIFolder = "$buildDir/generated"

swaggerSources {
  api {
    inputFile = file("$swaggerSourceFile")
    
    code {
      language = 'spring'
      configFile = file("$projectDir/api/config.json")
      outputDir = file("$openAPIFolder")
    }
    
  }
}




compileJava.dependsOn swaggerSources.api.code
compileJava.dependsOn generateSwaggerUI
sourceSets.main.java.srcDir "${swaggerSources.api.code.outputDir}/api"
sourceSets.main.resources.srcDir "${swaggerSources.api.code.outputDir}/api"


```
but I'm unable to view the documentation from the endpoint. I have tested

```
localhost:8080/swagger-ui-api/index.html
localhost:8080/index.html

```
Expected behavior: 

I would like to see the documentation served to the frontend

## Environment
Plugin version: 2.18.1
Swagger Codegen version: v3 / cli 3.0.5
Gradle version: 5.4
Java version: 11
OS: MacOs

**Comment by int128** [comment]
You can open the file on the browser. If you want to open it as http://localhost:8080, please set up a HTTP server.
