### ISSUE TITLE
Kotlin values not being generated properly for arrays and enums

### ISSUE THREAD

**Issue by AdityaAnand1** [int128/gradle-swagger-generator-plugin#182]
![image](https://user-images.githubusercontent.com/13274079/68771751-9a0d4c80-064e-11ea-802a-8012fcced056.png)

![image](https://user-images.githubusercontent.com/13274079/68771784-ad201c80-064e-11ea-871e-a3838d94e572.png)

**Comment by int128** [comment]
This seems an issue of the Swagger Codegen templates. Would you check the issues in https://github.com/swagger-api/swagger-codegen ?
