### ISSUE TITLE
Question: Is it possible to generate swagger-ui.yml from java source

### ISSUE THREAD

**Issue by ehmkah** [int128/gradle-swagger-generator-plugin#202]
I use your plugin for generating sourcecode from swagger.yml - no problems.

I read the documentation but I do not understand, whether it is possible to generate the swagger.yml file from the sourcecode. So my question is it possible with this plugin?

**Comment by int128** [comment]
No. You can generate YAML from code using language specific tools, e.g. https://github.com/springfox/springfox

**Comment by ehmkah** [comment]
Thanks for the fast answer.
