### ISSUE TITLE
Migrate away from jcenter

### ISSUE THREAD

**Issue by softprops** [int128/gradle-swagger-generator-plugin#219]
I'm looking for a good swagger codegen plugin and yours looks the nicest but I noticed you're still depending on jcenter. 

Jcenter will soon be shutdown breaking your plugin

https://blog.gradle.org/jcenter-shutdown

**Comment by LandDrag0n** [comment]
Would you consider also releasing the plugin with this commit as part of it? The latest version 2.8.12 is still using JCenter.
