### ISSUE TITLE
A Release hasn't been made since Feb 2020. Missing OAS3 verification which is in master

### ISSUE THREAD

**Issue by lkc0987** [int128/gradle-swagger-generator-plugin#239]
Hi, 

The code for verification of an OAS3 document was merged in early 2021, but a new release version hasn't been released since Feb 2020. Can we get a new release version with this fix?

**Comment by int128** [comment]
I released the new version with OAS3 support.
https://github.com/int128/gradle-swagger-generator-plugin/releases/tag/2.19.0
