### ISSUE TITLE
The latest release no longer supports Java 11

### ISSUE THREAD

**Issue by dishitd** [int128/gradle-swagger-generator-plugin#278]
## Describe the bug
After the latest release upgrade, plugin is not supporting Java 11. Is there any option available for supporting java 11?

To Reproduce:

Expected behavior:

## Environment
Plugin version: 2.19.0
Swagger Codegen version: 3
Gradle version: 7
Java version: 11
OS: MacOS

**Comment by riterdando** [comment]
I got the same problem. 
Looks like the latest release of the plugin should be reproduced, using JAVA 11.

**Comment by int128** [comment]
I set the compiler option in build.gradle but it seems not working. I will investigate it.

**Comment by riterdando** [comment]
Maybe something like this is working:

```
tasks.withType(JavaCompile) {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
}
```
