### ISSUE TITLE
Plugin wipes directory if outputDir = file('.')

### ISSUE THREAD

**Issue by synapticloop** [int128/gradle-swagger-generator-plugin#28]
When generating swagger code for a project, if the output directory is the current directory, the plugin (or something) deletes everything (including hidden directories).

plugin version: `id "org.hidetake.swagger.generator" version "2.1.2"`

```
generateSwaggerCode {
	language = 'java'
	inputFile = file('swagger-api/v1')
	configFile = file('config.json')
	outputDir = file('.')
}
```

**Comment by int128** [comment]
The plugin wipes the output directory to prevent side effect.

Added notice to README and parameter check.
