### ISSUE TITLE
JAVA 8 support for the plugin

### ISSUE THREAD

**Issue by riterdando** [int128/gradle-swagger-generator-plugin#283]
## Describe the feature

The latest release of the plugin uses JAVA 11 but some projects I work on, still are using JAVA 8.
I am using Gradle 7 in my build with JAVA 8 but now your plugin is not working in this setup.

I did a local checkout and test building the plugin using JAVA 8.
My modifications to `build.gradle` are simple:

```
sourceCompatibility = '1.8'
targetCompatibility = '1.8'
```

Building and testing, using the above settings were successful.

## Why do you want the feature?

Archieve compatibility with builds, still running JAVA 8.

__Can you provide a version of the plugin being compatible with JAVA 8?__

**Comment by mywill** [comment]
Having the same issue on legacy projects that are stuck on java 8 with versions > 2.18.2

**Comment by cmagnuson** [comment]
I'm also having the same issue on legacy projects.  

I changed source/target compatibility and all tests passed, opened PR #295 with these changes

**Comment by int128** [comment]
Merged #295
