### ISSUE TITLE
How to use a custom generator?

### ISSUE THREAD

**Issue by jonsie** [int128/gradle-swagger-generator-plugin#32]
According to the docs (for the swagger-codegen-cli tool), the `-l` flag can take a classname on the classpath.  So, in my generateSwaggerCode task I have specified something like:

```
generateSwaggerCode {
    language = 'CustomClientCodeGen'
    inputFile = file("${projectDir}/swagger/example.yml")
    configFile = file("${projectDir}/swagger/example.json")
}
```

I notice you are passing that directly to the `-l` option.  However, this does not work:

`Can't load config class with name CustomClientCodeGen`

Any thoughts?  I will need to take a closer look at your code later today.

**Comment by int128** [comment]
Maybe it is possible by creating a custom generator class at `buildSrc/src/main/groovy` in the project. I will try it later.

**Comment by int128** [comment]
Now 2.4.0 is available and supports a custom generator class. Please try it.

**Comment by jonsie** [comment]
@int128 Great news and nice job!  I will test this later today.
