### ISSUE TITLE
Swagger UI generation doesnt work with new Swagger UI 3.*

### ISSUE THREAD

**Issue by radai-rosenblatt** [int128/gradle-swagger-generator-plugin#40]
i just tried this:
```
dependencies {
  swaggerUI 'org.webjars:swagger-ui:3.0.6'
}
```
the generated index.html points to the example swagger petstore instead of my yaml file.
using 2.2.10 works as intended.

**Comment by oharaandrew314** [comment]
I've encountered this as well.  It would be nice for this to be updated.

**Comment by int128** [comment]
Now the plugin supports Swagger UI 3. Please try it.

**Comment by oharaandrew314** [comment]
Confirmed working with `swagger-ui 3.10.0`.  Any idea why it's not working with versions greater than that?  I get infinite spinners on all the methods.

**Comment by int128** [comment]
I got infinite spinners with `3.12.1` but all items show up once a toggle clicked.

I think this may be a bug of Swagger UI. I will bring up an issue on https://github.com/swagger-api/swagger-ui.

**Comment by int128** [comment]
This issue has been already fixed in the master branch of swagger-ui and it may be shipped in the next release (probably 3.14.0 or 3.13.1?). Thank you for the report, @oharaandrew314!

**Comment by oharaandrew314** [comment]
No problem.  Thanks for looking into it!

**Comment by int128** [comment]
Fixed now. Closing.
