### ISSUE TITLE
"components" can be filenames

### ISSUE THREAD

**Issue by bademux** [int128/gradle-swagger-generator-plugin#42]
With current configuration I can't specify files to be generated by swagger, like:
```xml
 <supportingFiles>ApiClient.java,ApiException.java,Configuration.java,JSON.java,Pair.java,StringUtil.java,TypeRef.java,ApiKeyAuth.java,Authentication.java,HttpBasicAuth.java,OAuth.java,OAuthFlow.java</supportingFiles>
```
"compenents" is restricted to ['apis', 'models', 'supportingFiles']

**Comment by kspar** [comment]
Is there a workaround?

**Comment by int128** [comment]
No workaround at this time. It will be supported in the next release.
