### ISSUE TITLE
Plugin removes project dir

### ISSUE THREAD

**Issue by bademux** [int128/gradle-swagger-generator-plugin#43]
Plugin cleanups dir it is bad behavior, as swagger has it's own .swagger-codegen-ignore

**Comment by int128** [comment]
The plugin always clean up an output directory because generated files should be ephemeral and not be committed in a Git repository. It keeps simple and prevent human errors.

**Comment by bademux** [comment]
@int128 thanks for an answer, but as I pointed swagger has it's own .swagger-codegen-ignore

**Comment by rschweda** [comment]
Maybe you could make this behaviour configurable? Like @bademux already said, there is an .swagger-codegen-ignore for this purpose. We actually don't want parts of the generated sources to be regenerated / deleted. This is also the default behaviour of the already exisiting Maven plugin for Swagger Codegen (where we are currently migrating from).

**Comment by johnrengelman** [comment]
This needs to be removed. The output directory is already marked with `@OutputDirectory`, so a user should "clean" the directory by running the associated clean command to remove the outputs.

This make it impossible to use the swagger ignore file to handle manually changes to the generated code.

**Comment by int128** [comment]
Would you tell me why you need `.swagger-codegen-ignore` behavior? What use case? I think it is bad practice. It causes generated result may differ depending on the environment, e.g. someone could compile it but others could not compile.

Anyway, I will add the feature to turn off wiping an output directory in the next release. Thank you for the proposal.

**Comment by bademux** [comment]
It is general idea, one who creates resourse is responsible for cleanup, imho
