### ISSUE TITLE
Java code generated isn't in outputDir but in outputDir/src/main/java

### ISSUE THREAD

**Issue by TruthNZ** [int128/gradle-swagger-generator-plugin#66]
With the following config:
```
swaggerSources {
	myProject {
		inputFile = file('swagger-api.json')
		code {
			language = 'spring'
			configFile = file('config.json')
			components = ['models']
			outputDir = file("$buildDir/swagger-code-myProject")
		}
	}
}
```
Generated files are not going to $buildDir/swagger-code-myProject as expected, but instead to $buildDir/swagger-code-myProject/src/main/java.

As such you cannot specify swaggerSources.livestreaming.code.outputDir as a valid input file for subsequent code handling.

**Comment by int128** [comment]
It is expected behavior that Swagger Codegen generates output into `$buildDir/swagger-code-*/src/main/java` due to the template of Swagger Codegen. Please specify that path for subsequent tasks.
