### ISSUE TITLE
No suchmethod while using the plugin java 8 

### ISSUE THREAD

**Issue by ramchjob** [int128/gradle-swagger-generator-plugin#96]
Below is the config

swaggerSources {
cemProfile {
	inputFile = file('src/main/resources/swagger/domain-openapi.yaml')
	code {
		language = 'spring'
		configFile = file('src/main/resources/swagger/domain-openapi.json')
	  }
  }
  
}

Client dependency 
swaggerCodegen 'io.swagger:swagger-codegen-cli:2.3.1'

When ran the command

 `gradle --stacktrace generateSwaggerCode`

:generateSwaggerCodeCemProfile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateSwaggerCodeCemProfile'.
> com.google.common.collect.ImmutableList.copyOf([Ljava/lang/Object;)Lcom/google/common/collect/ImmutableList;

Caused by : 
**java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.copyOf([Ljava/lang/Object;)Lcom/google/common/collect/ImmutableList;**

Checked the dependencies in the project and none of the projects refers to guava. 

JDK 1.8_152
Gradle 2.1.2

**Comment by int128** [comment]
The new release 2.12.0 may fix this issue. Would you try it?
